# Generated by Django 3.2.13 on 2023-04-02 17:10

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Выберите оценку', verbose_name='Оценка')),
                ('contest', models.ForeignKey(help_text='Выберите конкурс', on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='Конкурс')),
                ('contestant', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='track', chained_model_field='tracks', help_text='Выберите команду', on_delete=django.db.models.deletion.PROTECT, to='users.contestant', verbose_name='Команда')),
                ('criteria', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='stage', chained_model_field='stages', help_text='Выберите критерий', on_delete=django.db.models.deletion.PROTECT, to='contests.criteria', verbose_name='Критерий')),
                ('judge', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='track', chained_model_field='tracks', help_text='Выберите судью', on_delete=django.db.models.deletion.PROTECT, to='users.judge', verbose_name='Судья')),
                ('stage', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='contest', chained_model_field='contest', help_text='Выберите этап', on_delete=django.db.models.deletion.PROTECT, to='contests.stage', verbose_name='Этап')),
                ('track', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='contest', chained_model_field='contest', help_text='Выберите поток', on_delete=django.db.models.deletion.PROTECT, to='contests.track', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('contest', 'track', 'stage', 'criteria', 'judge', 'contestant'), name='unique_score_model'),
        ),
    ]
